### ISSUE TITLE
Not working on Android 

### ISSUE THREAD

**Issue by Emeecodes01** [ozlerhakan/poiji#65] opened 2018-11-01 04:43 UTC
Any time i try to write this library on android it always gives this error and the app crashes
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;

**Comment by ozlerhakan** [comment] 2018-11-01 06:54
Hi @Emeecodes01 ,

`DateTimeFormatter ` comes with Java 8. Currently, It's not compatible with Android.

**Comment by Emeecodes01** [comment] 2018-11-01 13:37
OK, so does it mean you can't use this library In Android?

**Comment by ozlerhakan** [comment] 2018-11-05 08:00
you can use poiji 1.16 or prior versions unless you use Java 1.8

**Comment by ozlerhakan** [comment] 2019-02-10 16:57
it's a duplicate of #21

**Closed by ozlerhakan** 2019-02-10 16:57 UTC
Labels: help wanted
